### ISSUE TITLE
Not able to set limits via systemd class

### ISSUE THREAD

**Issue by redcricket** [camptocamp/puppet-systemd#49]
I want to setup some systemd limits for a service so I have included ...

```
    include ::systemd
```
... in my manifest.  And I have this hiera data:

```
systemd::service_limits:
    'openstack-nova-compute.service':
        limits:
                LimitNOFILE: 32768
```

But when puppet on my node I get this error:

```
Error while evaluating a Function Call, Class[Systemd]: parameter 'service_limits' unrecognized key 'openstack-nova-compute.service' at ...
```

I have looked at the docs and they do not explain how to form the hash in hiera, they just give this example:

```
::systemd::service_limits { 'foo.service':
  limits => {
    'LimitNOFILE' => 8192,
    'LimitNPROC'  => 16384,
  }
}
```

So how would I do that in hiera/yaml?
